v0.19

diff --git a/common_AOK/usr_local_bin/check-env-compatible b/common_AOK/usr_local_bin/check-env-compatible
--- a/common_AOK/usr_local_bin/check-env-compatible
+++ b/common_AOK/usr_local_bin/check-env-compatible
@@ -56,8 +56,31 @@ uptime_check() {
     #  On Alpine >= 3.19  /usr/bin/uptime segfaults if procps is installed
     #  This gives a warning
     #
+
+    # Only relevant for Alpine
+    [ -f /etc/alpine-release ] || return
+
+    # if version check is not available, no check can be done
+    [ -f /opt/AOK/tools/vers_check.sh ] || {
+        echo "Unable to check Alpine version."
+        echo "If procps is installed on Alpine >= 3.19"
+        echo "/usr/bin/uptime will segfault."
+        return
+    }
+
+    . /opt/AOK/tools/vers_check.sh
+
+    # if older Alpine - all is good
+    ! min_version 3.19 && return
+
+    cmd_uptime=/usr/bin/uptime
+    [ "$(realpath "$cmd_uptime")" = /bin/busybox ] && return
+
+    rm -f "$cmd_uptime"
+    ln -sf /bin/busybox "$cmd_uptime"
+
     #region warning
-    warn="
+    notification "
 
 WARNING: If procps is installed on Alpine /usr/bin/uptime will segfault.
 
@@ -67,17 +90,6 @@ procps is updated and potentially installs an incompatible uptime.
 At that point this issue will be self corrected again.
 "
     #endregion
-
-    # Only relevant for Alpine
-    [ -f /etc/alpine-release ] || return
-
-    cmd_uptime=/usr/bin/uptime
-    [ "$(realpath "$cmd_uptime")" = /bin/busybox ] && return
-
-    rm -f "$cmd_uptime"
-    ln -sf /bin/busybox "$cmd_uptime"
-
-    notification "$warn"
 }
 
 #===============================================================
@@ -96,6 +108,11 @@ if [ "$1" = "wall" ]; then
 else
     use_wall=false
 fi
+
+[ ! -d /proc/ish ] && [ ! -f /etc/opt/AOK/this_fs_is_chrooted ] && {
+    notification "---  WARNING: $(basename "$0") - should only run on iSH"
+    exit 0
+}
 
 coreutils_check
 uptime_check
diff --git a/common_AOK/usr_local_bin/uptime b/common_AOK/usr_local_bin/uptime
--- a/common_AOK/usr_local_bin/uptime
+++ b/common_AOK/usr_local_bin/uptime
@@ -9,57 +9,58 @@
 #  This serves two purposes:
 #
 #  1> If lines like: ===  System startup  ===
-#     can be found in /var/log/syslog, the corresponding timestamp
-#     will be assumed to be iSH boot time, (will be off by a few seconds)
+#     can be found in /var/log/syslog, the corresponding timestamp for
+#     the last match will be assumed to be iSH boot time,
+#     (this will be off by a few seconds from actual iSH startup).
 #     Those lines are generated by the AOK inittab and aok_launcher.
 #     If it is not found this fallbacks to iOS boot time via /proc/uptime
 #     for Debian and for Alpine, the regular uptime is run instead showing
 #     the same iOS boot time.
 #
-#  2> In Debian on regular iSH, there is no /proc/loadavg
-#     This causes the regular uptime to fail.
-#     sysload is faked, always reporting 0.00
-#     Be aware that the lack of /proc/loadavg also causes other tools
-#     such as top & htop to fail!
+#  2> iSH doesnt currently provide /proc/loadavg
+#     Debians regular uptime fails badly - (because of no /proc/loadavg??)
+#     therefore sysload is faked, always reporting 0.00, 0.00, 0.00
+#     On Alpine the BusyBox uptime can report sysload, so sysload is
+#     extracted via /usr/bin/uptime.
 #
 
 show_help() {
-    echo "
+    #region help text
+    cat <<EOF
 Usage:
  uptime [options]
 
 Options:
  -p, --pretty   show uptime in pretty format
  -h, --help     display this help and exit
- -i, --ios      display iOS instead of iSH uptime
  -s, --since    system up since
  -V, --version  output version information and exit
 
-For more details see uptime(1)."
+<* non-standard options *>
+ -i, --ios      display iOS instead of iSH uptime
+ -l, --load     displays only sysload
+For more details see uptime(1).
+EOF
+    #endregion
     exit 0
 }
 
 org_uptime() {
-    # Security check that it isnt linking to itself...
     $dbg && echo ">org_uptime()" >/dev/stderr
 
-    _p="$(realpath "$(dirname -- "$0")")"
-    f_this="$_p/$prog_name"
     cmd_org=/usr/bin/uptime
 
-    [ -e /usr/bin/uptime ] || {
-        cmd_busybox=/bin/busybox
-        if [ -e "$cmd_busybox" ]; then
+    [ ! -x "$cmd_org" ] && {
+        if [ -x /bin/busybox ]; then
             echo "Linking $cmd_org to busybox"
-            ln -sf "$cmd_busybox" "$cmd_org"
+            ln -sf /bin/busybox "$cmd_org"
         else
             echo "ERROR: original $cmd_org unavailable!"
             exit 1
         fi
-        unset cmd_busybox
     }
 
-    [ "$(realpath "$cmd_org")" = "$f_this" ] && {
+    [ "$(realpath "$cmd_org")" = "$(realpath "$0")" ] && {
         echo "ERROR: $cmd_org points to this replacement uptime!"
         exit 1
     }
@@ -72,53 +73,38 @@ calculate_ish_uptime() {
     boot_time_epoch=$(date -d "$time_stamp_bootup" +%s)
     current_time=$(date +%s)
     uptime_seconds=$((current_time - boot_time_epoch))
-
-    unset boot_time_epoch current_time
 }
 
 calculate_ios_uptime() {
-    # Read the uptime from /proc/uptime
     $dbg && echo ">calculate_ios_uptime()" >/dev/stderr
-    uptime_raw="$(cut -d' ' -f1 </proc/uptime)"
+    uptime_raw=$(cut -d' ' -f1 </proc/uptime)
 
-    if test -d /proc/ish && grep -qiv aok /proc/ish/version 2>/dev/null; then
-        raw_s_hundreds="$(echo "$uptime_raw" | cut -d. -f1)"
-        raw_s="$(echo "$uptime_raw" | cut -d. -f2)"
-        uptime_seconds="$(echo "$raw_s_hundreds * 100 + $raw_s" | bc)"
+    if [ -d /proc/ish ] && grep -qiv aok /proc/ish/version 2>/dev/null; then
+        raw_s_hundreds=$(echo "$uptime_raw" | cut -d. -f1)
+        raw_s=$(echo "$uptime_raw" | cut -d. -f2)
+        uptime_seconds=$(echo "$raw_s_hundreds * 100 + $raw_s" | bc)
     else
-        uptime_seconds="$uptime_raw"
+        uptime_seconds=$(echo "$uptime_raw" | awk '{print int($1)}')
     fi
-
-    unset uptime_raw
-    unset raw_s_hundreds
-    unset raw_s
 }
 
 calculate_uptime() {
+    startup_notice="===  System startup  ==="
     $dbg && echo ">calculate_uptime()" >/dev/stderr
-    time_stamp_bootup="$(grep "System startup" /var/log/syslog |
-        tail -n 1 | awk '{print $1" "$2}')"
+    time_stamp_bootup="$(grep "$startup_notice" /var/log/syslog |
+        tail -n 1 |
+        awk '{print $1" "$2}')"
     if [ -n "$time_stamp_bootup" ] && ! $force_ios_uptime; then
         calculate_ish_uptime
-    elif [ -f /etc/alpine-release ] && [ -z "$alpine_options" ]; then
-        #
-        # if org_uptime is a binary and not a soft link to busybox
-        # it would be able to handle options, but instead of detecting
-        # that its simpler to use calculate_ios_uptime
-        #
-        org_uptime # use the normal uptime
-        exit 0
     else
         calculate_ios_uptime
     fi
 
     $dbg && echo ">calculate_uptime() - doing the calculations" >/dev/stderr
-    # Calculate days, hours, minutes, and seconds
-    ut_weeks=$(echo "$uptime_seconds / 86400 / 7" | bc)
-    ut_days=$(echo "$uptime_seconds / 86400" | bc)
-    ut_hours=$(echo "($uptime_seconds % 86400) / 3600" | bc)
-    ut_minutes=$(echo "($uptime_seconds % 3600) / 60" | bc)
-    # ut_seconds=$(echo "$uptime_seconds % 60" | bc)
+    # Calculate days, hours, minutes
+    ut_days=$((uptime_seconds / 86400))
+    ut_hours=$(((uptime_seconds % 86400) / 3600))
+    ut_minutes=$(((uptime_seconds % 3600) / 60))
 }
 
 display_sysload() {
@@ -132,56 +118,43 @@ display_sysload() {
 }
 
 show_pretty() {
+    $dbg && echo ">show_pretty()" >/dev/stderr
     output="$ut_minutes minutes"
     [ "$ut_hours" -gt 0 ] && output="$ut_hours hours, $output"
     [ "$ut_days" -gt 0 ] && output="$ut_days days, $output"
-    [ "$ut_weeks" -gt 0 ] && output="$ut_weeks weeks, $output"
-
     echo "up $output"
 }
 
 show_since() {
-    date -d "$uptime_seconds seconds ago" "+%Y-%m-%d %H:%M:%S"
+    $dbg && echo ">show_since($uptime_seconds)" >/dev/stderr
+    if [ -f /etc/alpine-release ]; then
+        current_timestamp=$(date +%s)
+        new_timestamp=$((current_timestamp - uptime_seconds))
+        date -u -d "@$new_timestamp" "+%Y-%m-%d %H:%M:%S"
+    else
+        date -d "$uptime_seconds seconds ago" "+%Y-%m-%d %H:%M:%S"
+    fi
 }
 
 show_version() {
+    $dbg && echo ">show_version()" >/dev/stderr
     _f=/etc/aok-fs-release
-    if [ -f "$_f" ]; then
-        aok_vers="$(cat "$_f")"
-    else
-        aok_vers="unknown AOK-FS version"
-    fi
+    aok_vers=$(cat "$_f" 2>/dev/null || echo "unknown AOK-FS version")
     echo "uptime from AOK-FS $aok_vers"
-
-    unset aok_vers
+    exit 0
 }
 
 default_view() {
-    # Print the uptime in the format used by uptime command
     $dbg && echo ">default_view()" >/dev/stderr
-    # < 1h
-    # 17:42:51 up 27 min,  1 user,
 
-    $dbg && echo ">default_view() - minutes" >/dev/stderr
-    if [ "$ut_minutes" -lt 10 ]; then
-        _minutes=$(printf "0%d" "$ut_minutes")
-    else
-        _minutes=$(printf "%d" "$ut_minutes")
-    fi
-
-    $dbg && echo ">default_view() - hours" >/dev/stderr
-    if [ "$ut_hours" -lt 10 ]; then
-        _hours=$(printf " %d" "$ut_hours")
-    else
-        _hours=$(printf "%d" "$ut_hours")
-    fi
+    _minutes=$(printf "%02d" "$ut_minutes")
+    _hours=$(printf "%d" "$ut_hours")
 
     output="$ut_minutes min"
     [ "$ut_hours" -gt 0 ] && output="$_hours:$_minutes"
     [ "$ut_days" -gt 0 ] && output="$ut_days days, $output"
-    [ "$ut_weeks" -gt 0 ] && output="$ut_weeks weeks, $output"
 
-    user_count="$(find /dev/pts/* | wc -l)"
+    user_count=$(find /dev/pts/* | wc -l)
     user_field="$user_count user"
     [ "$user_count" -gt 1 ] && user_field="${user_field}s"
 
@@ -199,25 +172,16 @@ default_view() {
 
 force_ios_uptime=false
 display_mode="default"
-# if Alpine uptime is used this provides the desired options
-alpine_options=""
 dbg=false
-
-prog_name="$(basename "$0")"
 
 while [ -n "$1" ]; do
     case "$1" in
     -h | --help) show_help ;;
     -d) dbg=true ;;
     -i | --ios) force_ios_uptime=true ;;
-    -p | --pretty)
-        display_mode="pretty"
-        alpine_options="$alpine_options -p"
-        ;;
-    -s | --since)
-        display_mode="since"
-        alpine_options="$alpine_options -s"
-        ;;
+    -l | --load) display_mode="load" ;;
+    -p | --pretty) display_mode="pretty" ;;
+    -s | --since) display_mode="since" ;;
     -V | --version) show_version ;;
     *)
         echo "uptime: invalid option -- '$1'"
@@ -233,6 +197,7 @@ case "$display_mode" in
 default) default_view ;;
 pretty) show_pretty ;;
 since) show_since ;;
+load) display_sysload ;;
 *)
     echo "Invalid display_mode [$display_mode]"
     ;;
