improved param handling

diff --git a/common_AOK/usr_local_bin/uptime b/common_AOK/usr_local_bin/uptime
--- a/common_AOK/usr_local_bin/uptime
+++ b/common_AOK/usr_local_bin/uptime
@@ -41,20 +41,34 @@ For more details see uptime(1)."
 
 org_uptime() {
     # Security check that it isnt linking to itself...
+    $dbg && echo ">org_uptime()" >/dev/stderr
 
     _p="$(realpath "$(dirname -- "$0")")"
     f_this="$_p/$prog_name"
     cmd_org=/usr/bin/uptime
 
+    [ -e /usr/bin/uptime ] || {
+        cmd_busybox=/bin/busybox
+        if [ -e "$cmd_busybox" ]; then
+            echo "Linking $cmd_org to busybox"
+            ln -sf "$cmd_busybox" "$cmd_org"
+        else
+            echo "ERROR: original $cmd_org unavailable!"
+            exit 1
+        fi
+        unset cmd_busybox
+    }
+
     [ "$(realpath "$cmd_org")" = "$f_this" ] && {
         echo "ERROR: $cmd_org points to this replacement uptime!"
         exit 1
     }
-    $cmd_org $@
+    $dbg && echo ">org_uptime() - running org_uptime" >/dev/stderr
+    $cmd_org
 }
 
 calculate_ish_uptime() {
-    $dbg && echo ">calculate_ish_uptime()"
+    $dbg && echo ">calculate_ish_uptime()" >/dev/stderr
     boot_time_epoch=$(date -d "$time_stamp_bootup" +%s)
     current_time=$(date +%s)
     uptime_seconds=$((current_time - boot_time_epoch))
@@ -64,7 +78,7 @@ calculate_ish_uptime() {
 
 calculate_ios_uptime() {
     # Read the uptime from /proc/uptime
-    $dbg && echo ">calculate_ios_uptime()"
+    $dbg && echo ">calculate_ios_uptime()" >/dev/stderr
     uptime_raw="$(cut -d' ' -f1 </proc/uptime)"
 
     if test -d /proc/ish && grep -qiv aok /proc/ish/version 2>/dev/null; then
@@ -81,19 +95,24 @@ calculate_ios_uptime() {
 }
 
 calculate_uptime() {
-    $dbg && echo ">calculate_uptime()"
+    $dbg && echo ">calculate_uptime()" >/dev/stderr
     time_stamp_bootup="$(grep "System startup" /var/log/syslog |
         tail -n 1 | awk '{print $1" "$2}')"
     if [ -n "$time_stamp_bootup" ] && ! $force_ios_uptime; then
         calculate_ish_uptime
-    elif [ -f /etc/alpine-release ]; then
-        # shellcheck disable=SC2248
-        org_uptime $alpine_options # use the normal uptime
+    elif [ -f /etc/alpine-release ] && [ -z "$alpine_options" ]; then
+        #
+        # if org_uptime is a binary and not a soft link to busybox
+        # it would be able to handle options, but instead of detecting
+        # that its simpler to use calculate_ios_uptime
+        #
+        org_uptime # use the normal uptime
         exit 0
     else
         calculate_ios_uptime
     fi
 
+    $dbg && echo ">calculate_uptime() - doing the calculations" >/dev/stderr
     # Calculate days, hours, minutes, and seconds
     ut_weeks=$(echo "$uptime_seconds / 86400 / 7" | bc)
     ut_days=$(echo "$uptime_seconds / 86400" | bc)
@@ -103,7 +122,9 @@ calculate_uptime() {
 }
 
 display_sysload() {
+    $dbg && echo ">display_sysload()" >/dev/stderr
     if [ -f /etc/alpine-release ]; then
+        $dbg && echo ">display_sysload() - using org_uptime" >/dev/stderr
         org_uptime | sed 's/load average: /|/' | cut -d'|' -f 2
     else
         echo "0.00, 0.00, 0.00"
@@ -120,11 +141,6 @@ show_pretty() {
 }
 
 show_since() {
-    if [ -f /etc/alpine-release ]; then
-        echo "Alpine only supports since for iOS uptime:"
-        org_uptime -s
-        exit 0
-    fi
     date -d "$uptime_seconds seconds ago" "+%Y-%m-%d %H:%M:%S"
 }
 
@@ -142,16 +158,18 @@ show_version() {
 
 default_view() {
     # Print the uptime in the format used by uptime command
-
+    $dbg && echo ">default_view()" >/dev/stderr
     # < 1h
     # 17:42:51 up 27 min,  1 user,
 
+    $dbg && echo ">default_view() - minutes" >/dev/stderr
     if [ "$ut_minutes" -lt 10 ]; then
         _minutes=$(printf "0%d" "$ut_minutes")
     else
         _minutes=$(printf "%d" "$ut_minutes")
     fi
 
+    $dbg && echo ">default_view() - hours" >/dev/stderr
     if [ "$ut_hours" -lt 10 ]; then
         _hours=$(printf " %d" "$ut_hours")
     else
@@ -167,6 +185,7 @@ default_view() {
     user_field="$user_count user"
     [ "$user_count" -gt 1 ] && user_field="${user_field}s"
 
+    $dbg && echo ">default_view() - create output [$output] [$user_field]" >/dev/stderr
     _s=" $(date +%H:%M:%S) up $output,  $user_field,  load average:"
     _s="$_s $(display_sysload)"
     echo "$_s"
@@ -191,10 +210,13 @@ while [ -n "$1" ]; do
     -h | --help) show_help ;;
     -d) dbg=true ;;
     -i | --ios) force_ios_uptime=true ;;
-    -p | --pretty) display_mode="pretty" ;; # option not suported by busybox
+    -p | --pretty)
+        display_mode="pretty"
+        alpine_options="$alpine_options -p"
+        ;;
     -s | --since)
         display_mode="since"
-        alpine_options="-s"
+        alpine_options="$alpine_options -s"
         ;;
     -V | --version) show_version ;;
     *)
