refactored bootup and shutdown

diff --git a/common_AOK/usr_local_sbin/aok_launcher b/common_AOK/usr_local_sbin/aok_launcher
--- a/common_AOK/usr_local_sbin/aok_launcher
+++ b/common_AOK/usr_local_sbin/aok_launcher
@@ -23,17 +23,15 @@
 #
 
 log_it() {
-    # In recovery mode, skip logging to minimize risk of issues
+    # In recovery-mode, skip logging to minimize risk of issues
     [ -f "$f_recovery_mode" ] && return
 
     # if no supported loggers are found, fall back to a non-dependency solution
-    f_logger=/usr/local/bin/logger
-    if [ -x "$f_logger" ]; then
-        "$f_logger" "$prog_name" "$*"
+    if [ -x "$cmd_logger" ]; then
+        "$cmd_logger" "$prog_name" "$*"
     else
         echo "$(date +"%Y-%m-%d %H:%M:%S") ${prog_name}: $*" >>/var/log/messages
     fi
-    unset f_logger
 }
 
 print_log() {
@@ -54,16 +52,55 @@ print_log() {
     log_it "$msg"
 }
 
-check_for_revovery_mode() {
-    if [ -f "$f_this_is_chrooted" ]; then
-        #
-        #  On iSH boot there is time to press r during boot wait
-        #  when chrooted there is no boot wait, so we make a short wait
-        #  instead, to make recovery available
-        #
-        sleep 0.7
-    fi
+fix_stdio_device() {
+    dev_src="$1"
+    dev_name="/dev/$2"
 
+    [ -c "$dev_name" ] || {
+        echo "Fixing $dev_name"
+        rm -f "$dev_name"
+        ln -sf "$dev_src" "$dev_name"
+    }
+    return 0
+}
+
+fix_stdio() {
+    #
+    # on iSH stdio sometimes are missing, this ensures
+    # their pressence
+    #
+    [ ! -d /proc/ish ] && return # only do on ish
+
+    fix_stdio_device /proc/self/fd/0 stdin
+    fix_stdio_device /proc/self/fd/1 stdout
+    fix_stdio_device /proc/self/fd/2 stderr
+}
+
+update_deb_log_kill_cmd() {
+    #
+    #  Since the cmd_tail might change, always
+    #  update the kill cmd to its current definition
+    #
+    _f=/usr/local/sbin/kill_tail_logging
+    #region kill_tail_logging cmd
+    echo "#!/bin/sh
+#  Called from /usr/local/bin/console-restart
+#  Replaced by /usr/local/sbin/aok_launcher during each reboot
+
+(
+    echo
+    echo 'Console tailing of /var/log/* will be restarted'
+    echo 'Non text-files will be ignored'
+) >/dev/console
+
+pgrep -f \"$cmd_tail\" | xargs -r kill
+" >"$_f"
+    #endregion
+    chown root: "$_f"
+    chmod 744 "$_f"
+}
+
+check_for_recovery_mode() {
     # Disable terminal line buffering and enable read without Enter
     stty -icanon min 0 time 0
 
@@ -76,49 +113,77 @@ check_for_revovery_mode() {
     # Check if a key was pressed
     case "$keypress" in
     "r" | "R")
-        trap '' INT # abort capturing Ctrl-C
+        # First do urgent tasks that are somewhat time sensitive
         touch "$f_recovery_mode"
+        trap '' INT # abort capturing Ctrl-C
+
+        f_recovery_mode_log=/var/log/recovery-mode.log
+
+        fix_stdio
         echo
-        echo "===  recovery node selected  ==="
-        if [ -x /bin/ash ]; then
-            cmd="/bin/ash"
-        else
-            cmd="/bin/bash"
-        fi
-        echo "---  Starting $cmd, on exit App will terminate"
-        echo "---  /etc/inittab processing was canceled"
-        echo "---  Be aware, this is a bare shell!"
-        echo "In order to maximize chances of recovery, in case shell init-scripts are faulty,"
-        echo "shell is not a login session. Most likely PATH is minimal!"
-        echo
-        $cmd
-        echo "Clearing recovery mode"
+        echo "===  recovery-mode selected  ==="
+        echo "---  Starting rescue shell - on exit, App will terminate."
+        [ ! -f "$f_pts_0_as_console" ] && {
+            echo "---  inittab acions cancelled by recovery-mode are logged in:"
+            echo "---    $f_recovery_mode_log"
+            echo "---  This file will be removed when exiting recovery-mode!"
+        }
+        #region recovery explaination
+        echo "
+---  Be aware, this is  /bin/sh  in order to maximize chances of recovery,
+---  in case shell init-scripts are faulty. Most likely PATH is minimal!
+"
+        #endregion
+        stty sane
+        /bin/sh -i
+
+        echo "Clearing recovery-mode"
         rm -f "$f_recovery_mode"
-        sleep 2
-        exit 1
+        rm -f "$f_recovery_mode_log"
+        sleep 1
+        exit 1 # exit App on iPad, reboot on iPhone
         ;;
     *) ;;
     esac
 }
 
 indicate_end_of_recovery_window() {
-    echo "recovery mode no longer possible"
+    if [ -f "$f_this_is_chrooted" ]; then
+        #
+        #  On iSH boot there is time to press r during boot wait
+        #  when chrooted there is no boot wait, so we make a short wait
+        #  instead, to make recovery available
+        #
+        sleep 0.7
+    fi
+    check_for_recovery_mode
+    echo "recovery-mode no longer possible"
+    echo
+    # remove any left-over recovery logs
+    rm -f /var/log/recovery-mode.log
 }
 
 display_header() {
     if [ -f "$f_aok_release" ]; then
-        aok_vers="$(cat "$f_aok_release" 2>/dev/null)" || aok_vers="*** Failed to read $f_aok_release ***"
+        aok_vers="$(cat "$f_aok_release" 2>/dev/null)" ||
+            aok_vers="*** Failed to read $f_aok_release ***"
     else
         aok_vers=Unknown
     fi
 
     if test -f "$f_rel_alpine"; then
-        fs_name="Alpine $(cat "$f_rel_alpine" 2>/dev/null)" || fs_name="Alpine Unknown"
+        fs_name="Alpine $(cat "$f_rel_alpine" 2>/dev/null)" ||
+            fs_name="Alpine Unknown"
     elif test -f "$f_rel_devuan"; then
-        #  Devuan must come before Debian, since it also has thr f_rel_debian file
-        fs_name="Devuan $(cat "$f_rel_devuan" 2>/dev/null)" || fs_name="Devuan Unknown"
+        #
+        #  Devuan must come before Debian, since it also has the
+        #  f_rel_debian file
+        #
+        fs_name="Devuan $(cat "$f_rel_devuan" 2>/dev/null)" ||
+            fs_name="Devuan Unknown"
     elif test -f "$f_rel_debian"; then
-        fs_name="Debian $(cat "$f_rel_debian" 2>/dev/nul)" || fs_name="Debian Unknown"
+        fs_name="Debian $(cat "$f_rel_debian" 2>/dev/null)" ||
+            fs_name="Debian Unknown"
     else
         fs_name=Unknown
     fi
@@ -130,7 +195,7 @@ display_header() {
             "no session will be started in this vterm"
     }
     $this_is_pts0 && {
-        echo "Press 'r' during bootup for recovery mode"
+        echo "Press 'r' during bootup for recovery-mode"
         echo
     }
 
@@ -139,12 +204,94 @@ display_header() {
 }
 
 kill_console_tail() {
-    pgrep -f 'tail -n 0 -f /var/log/' | xargs -r kill
+    #
+    #  Only usable by Alpine, Debian uses console-restart, since the tail
+    #  cmd isnt properly tied to /dev/pts/0 and thus cant recieve Ctrl-C
+    #
+    echo
+    echo "Console tailing of /var/log/* will be restarted"
+    echo "Non text-files will be ignored"
+    pgrep -f "$cmd_tail" | xargs -r kill
+}
+
+select_log_files_to_monitor() {
+    #
+    #  Add all text files in logdir
+    #
+    log_files=""
+    d_logs=/var/log
+
+    # shellcheck disable=SC2045
+    for log_file in $(ls -t "$d_logs"); do
+        #log_basename="$(basename "$logfile")"
+        f_log_file="$d_logs/$log_file"
+        [ ! -f "$f_log_file" ] && continue               # not a file
+        file -b "$f_log_file" | grep -q text || continue # not a text file
+        log_files="$log_files $f_log_file"
+    done
+}
+
+handle_custom_console_monitor() {
+    #
+    #  If a custom console monitor is used, remember to touch
+    #  $f_inittab_can_start once it is setup, so that inittab
+    #  can commence its run
+    #
+    echo "><> running $cmd_custom_console_monitor"
+    $cmd_custom_console_monitor "$boot_time"
+    #
+    #  Should not get here...
+    #
+    echo "ERROR: exited: $cmd_custom_console_monitor"
+    echo "       Will shut down in 30s"
+    sleep 30
+    exit 1
+}
+
+monitor_log_files() {
+    initial_console_run=true
+
+    echo "Console tailing of /var/log/* - non text-files will be ignored"
+    trap 'kill_console_tail' INT
+    while true; do
+        select_log_files_to_monitor
+        if [ -f "$f_rel_alpine" ]; then
+            # allow restart of tail cmd
+            msg="Press Ctrl-C to re-read logfiles"
+        else
+            # Ctrl-C not usable for this on Debian...
+            # this tail is not tied to a pts
+            msg="Run console-restart to re-read logfiles"
+        fi
+        echo "Entries without timestamp are typically console printouts"
+        echo "$msg"
+        echo
+        $initial_console_run && {
+            initial_console_run=false
+            (
+                #
+                # run in bg with a sleep so that tail can start
+                # before inittab commences
+                #
+                sleep 1
+                touch "$f_inittab_can_start"
+            ) &
+        }
+        # shellcheck disable=SC2086 # log_files should be expanded
+        $cmd_tail $log_files 2>/dev/null
+        sleep 1
+    done
+
+    echo "ERROR: Exited console monitoring loop - shouldnt happen"
+    echo "       Will shut down in 30s"
+    sleep 30
+    exit 1 # shouldnt get here, but just in case
 }
 
 bootup() {
     # at bootup also log it
     if [ -f "$f_pts_0_as_console" ]; then
+        check_for_recovery_mode
         [ "$(stat -c "%t %T" /dev/console)" != "88 0" ] && {
             echo "Setting up /dev/pts/0 as console"
             rm -f /dev/console && mknod -m 222 /dev/console c 136 0
@@ -152,31 +299,20 @@ bootup() {
 
         /usr/local/bin/network-check.sh
         indicate_end_of_recovery_window
-        check_for_revovery_mode
 
-        trap 'kill_console_tail' INT # allow restart of tail cmd
-        # while loop restarts tail after Ctrl-C
-        while true; do
-            echo
-            if [ -f "$f_rel_alpine" ]; then
-                echo "Tailing /var/log/*log - Press Ctrl-C to re-read logfiles"
-            else
-                # Ctrl-C not usable for this on Debian...
-                # this tail is not tied to a pts
-                echo "Tailing /var/log/*log - run console-restart to re-read"
-            fi
-            tail -n 0 -f /var/log/*log 2>/dev/null
-        done
-        exit 0 # shouldnt get here, but just in case
+        if [ -x "$cmd_custom_console_monitor" ]; then
+            handle_custom_console_monitor
+        else
+            monitor_log_files
+        fi
     else
         [ "$(stat -c "%t %T" /dev/console)" != "5 1" ] && {
             echo "Reverting console to normal mode"
             rm -f /dev/console && mknod -m 666 /dev/console c 5 1
         }
+        /usr/local/bin/network-check.sh
+        indicate_end_of_recovery_window
     fi
-
-    /usr/local/bin/network-check.sh
-    check_for_revovery_mode
 
     if [ ! -f "$f_this_is_chrooted" ]; then
         runlevel_wait
@@ -207,7 +343,6 @@ deploy_aok() {
     #  continue the deploy
     #
     indicate_end_of_recovery_window
-    check_for_revovery_mode
     echo
     echo "******************************************************"
     echo "*                                                    *"
@@ -262,22 +397,25 @@ deploy_aok() {
 
 set_abort_runlevel_wait() {
     echo
-    print_log "***  Ctrl-C captured - aborting wait for runlevel $expected_runlevel  ***"
+    _s="***  Ctrl-C captured - aborting wait for runlevel"
+    _s="$_s $expected_runlevel  ***"
+    print_log "$_s"
     echo
     abort_runlevel_wait=1
 }
 
 runlevel_wait() {
-    trap 'set_abort_runlevel_wait INT' INT
+    trap 'set_abort_runlevel_wait' INT
 
     while true; do
-        check_for_revovery_mode
+        check_for_recovery_mode
         current_runlevel="$(rc-status -r)"
         if [ "$current_runlevel" = "$expected_runlevel" ]; then
             echo "runlevel is now '$expected_runlevel'"
             break
         fi
-        echo "current runlevel is $current_runlevel - waiting for $expected_runlevel - press Ctrl-C to abort wait"
+        _s="current runlevel is $current_runlevel - waiting for"
+        _s="$_s $expected_runlevel - press Ctrl-C to abort wait"
         sleep 2
         [ -f "$f_recovery_mode" ] && return
         [ "$abort_runlevel_wait" = "1" ] && break
@@ -301,16 +439,23 @@ login_with_param_check() {
     #
     #  Do this for each login, in case changes have been made
     #
-    if [ "$ignore_login_params" != "1" ] && [ -f "$f_login_default_user" ]; then
+    if [ "$ignore_login_params" != "1" ] &&
+        [ -f "$f_login_default_user" ]; then
+
         def_user="$(cat "$f_login_default_user")"
         [ -n "$def_user" ] && {
             cut -d: -f 1 /etc/passwd | grep -qw "$def_user" || {
                 echo
-                print_log "ERROR: default user for autologin: $def_user is not valid"
+                _s="ERROR: default user for autologin: $def_user"
+                _s="$_s is not valid"
+                print_log "$_s"
                 print_log "reverting to basic no params login"
                 echo
                 ignore_login_params=1
-                #  it should be safe to recuser once, sice param checks are disabled
+                #
+                #  it should be safe to recuser once, sice param checks
+                #  are disabled
+                #
                 login_with_param_check
                 return
             }
@@ -323,11 +468,16 @@ login_with_param_check() {
         "$f_login_prog" $login_params || {
             _excode="$?"
             echo
-            print_log "ERROR: $f_login_prog exited with: $_excode, trying to use params: $login_params"
+            _s="ERROR: $f_login_prog exited with: $_excode,"
+            _s="$_s trying to use params: $login_params"
+            print_log "$_s"
             print_log "reverting to basic no params login"
             echo
             ignore_login_params=1
-            #  it should be safe to recuser once, sice param checks are disabled
+            #
+            #  it should be safe to recuser once, sice param checks
+            #  are disabled
+            #
             login_with_param_check
             return
         }
@@ -344,11 +494,78 @@ login_with_param_check() {
     fi
 }
 
+handle_logins() {
+    while true; do
+        #
+        #  Ensure params are tried for each login attempt, in case they
+        #  have been changed during the current session, and continous
+        #  logins is set
+        #
+        ignore_login_params=0
+        login_with_param_check
+        login_ex_code="$?"
+        [ "$login_ex_code" != "0" ] && {
+            echo
+            print_log "ERROR: $f_login_prog exited with: $login_ex_code"
+        }
+
+        if [ -f "$f_this_is_chrooted" ]; then
+            _s="This is chrooted, always terminating on logout,"
+            _s="$_s this should also exit the chroot"
+            print_log "$_s"
+            exit 0
+        fi
+
+        if [ -f "$f_logins_continous" ]; then
+            echo
+            _s="Will spawn a new login session. If this is not requested,"
+            _s="$_s run aok"
+            print_log "$_s"
+            echo
+            sleep 1
+        else
+            # echo
+            # echo "To enable continous vterm sessions, run aok"
+            if $this_is_pts0; then
+                # echo
+                # echo "Shutting down system..."
+                # echo
+                /usr/local/bin/shutdown now
+                _s="ERROR: Returned from shutdown - should NOT happen!"
+                print_log "$_s"
+                echo "><> sleeping 30"
+                sleep 30
+            else
+                print_log "Terminating vterm $(tty)"
+                sleep 2
+                exit
+            fi
+        fi
+    done
+
+    _s="===  Fell out of infinite aok_launcher login loop -"
+    _s="$_s Should really not happen!"
+    print_log "$_s"
+    echo "will sleep forever, please shutdown iSH"
+    /bin/sleep infinity
+}
+
 #===============================================================
 #
 #   Main
 #
 #===============================================================
+
+state_prefix=/etc/opt/AOK
+f_pts_0_as_console="$state_prefix"/pts_0_as_console
+f_recovery_mode="$state_prefix"/recovery-mode
+f_inittab_can_start="$state_prefix"/inittab_can_start
+
+#  Ensure no left-overs from a previous boot
+rm -f "$f_inittab_can_start"
+rm -f "$f_recovery_mode"
+
+check_for_recovery_mode
 
 prog_name=$(basename "$0")
 expected_runlevel="default"
@@ -356,30 +573,35 @@ expected_runlevel="default"
 f_issue_file="/etc/issue"
 f_login_prog="/bin/login"
 
-state_prefix=/etc/opt/AOK
 f_deploy_state="$state_prefix"/deploy_state
 f_logins_continous="$state_prefix"/login-continous
 f_login_default_user="$state_prefix"/login-default-username
-f_pts_0_as_console="$state_prefix"/pts_0_as_console
-f_recovery_mode="$state_prefix"/recovery-mode
 f_profile_hints="$state_prefix"/show_profile_hints
 f_this_is_chrooted="$state_prefix"/this_fs_is_chrooted
-
 f_aok_release=/etc/aok-fs-release
 f_rel_alpine=/etc/alpine-release
 f_rel_devuan=/etc/devuan_version
 f_rel_debian=/etc/debian_version
+
+cmd_logger=/usr/local/bin/logger
+cmd_custom_console_monitor=/usr/local/sbin/custom_console_monitor
+cmd_tail="tail -n 0 -f "
 
 if [ "$(tty)" = "/dev/pts/0" ]; then
     this_is_pts0=true
 else
     this_is_pts0=false
 fi
-
-rm -f "$f_recovery_mode" #  Ensure this isn't left from a previous boot
-
-check_for_revovery_mode
+check_for_recovery_mode
+$this_is_pts0 && {
+    boot_time=$(date '+%Y-%m-%d %H:%M:%S')
+    echo "Booted at: $boot_time"
+}
+fix_stdio
+[ -f "$f_rel_debian" ] && update_deb_log_kill_cmd
+check_for_recovery_mode
 display_header
+echo "aok_monitor tty [$(tty)]"
 
 #  If deploy has not completed - handle it
 if [ -f "$f_deploy_state" ]; then
@@ -387,62 +609,9 @@ if [ -f "$f_deploy_state" ]; then
 else
     if $this_is_pts0; then
         bootup # if /dev/console is used, pts/0 will not exit this
-        indicate_end_of_recovery_window
-        check_for_revovery_mode
     else
         /usr/local/bin/network-check.sh
     fi
 fi
 
-#
-#  This is only run on first vterm
-#
-
-while true; do
-    #
-    #  Ensure params are tried for each login attempt, in case they have
-    #  been changed during the current session, and continous logins is set
-    #
-    ignore_login_params=0
-    login_with_param_check
-    login_ex_code="$?"
-    [ "$login_ex_code" != "0" ] && {
-        echo
-        print_log "ERROR: $f_login_prog exited with: $login_ex_code"
-    }
-
-    if [ -f "$f_this_is_chrooted" ]; then
-        print_log "This is chrooted, always terminating on logout, this should also exit the chroot"
-        exit 0
-    fi
-
-    if [ -f "$f_logins_continous" ]; then
-        echo
-        print_log "Will spawn a new login session. If this is not requested, run aok"
-        echo
-        sleep 1
-    else
-        echo
-        echo "To enable continous vterm sessions, run aok"
-        if $this_is_pts0; then
-            echo
-            echo "Shutting down..."
-            echo
-            if [ -f "$f_rel_alpine" ]; then
-                /usr/local/sbin/halt
-            else
-                halt
-            fi
-            msg="ERROR: Returned from halt - should NOT happen!"
-            echo "$msg" | tee -a /var/log/syslog
-        else
-            print_log "Terminating vterm $(tty)"
-            sleep 2
-            exit
-        fi
-    fi
-done
-
-print_log "===  Fell out of infinite aok_launcher loop - Should really not happen!"
-echo "will sleep forever, please shutdown iSH"
-/bin/sleep infinity
+handle_logins
