lintconfig

diff --git a/Alpine/usr_local_bin/aok-groups b/Alpine/usr_local_bin/aok-groups
--- a/Alpine/usr_local_bin/aok-groups
+++ b/Alpine/usr_local_bin/aok-groups
@@ -9,34 +9,34 @@
 check_for_option() {
     case "$1" in
 
-    "" | "-h" | "--help")
-        echo "usage: $prog_name [-h] | [-g] | [-l] | | group1 group2 -group3 ..."
-        echo
-        echo "This is a tool to install/uninstall groups of packages"
-        echo "prefixing a group name with - means uninstall that group"
-        echo
-        echo "options:"
-        echo "  -h, --help   show this help message and exit"
-        echo "  -g           list available groups and exit"
-        echo "  -l           list groups and items and exit"
-        echo
-        exit 0
-        ;;
+        "" | "-h" | "--help")
+            echo "usage: $prog_name [-h] | [-g] | [-l] | | group1 group2 -group3 ..."
+            echo
+            echo "This is a tool to install/uninstall groups of packages"
+            echo "prefixing a group name with - means uninstall that group"
+            echo
+            echo "options:"
+            echo "  -h, --help   show this help message and exit"
+            echo "  -g           list available groups and exit"
+            echo "  -l           list groups and items and exit"
+            echo
+            exit 0
+            ;;
 
-    "-g")
-        task="groups"
-        process_items
-        echo
-        exit 0
-        ;;
+        "-g")
+            task="groups"
+            process_items
+            echo
+            exit 0
+            ;;
 
-    "-l")
-        task="list"
-        process_items
-        exit 0
-        ;;
+        "-l")
+            task="list"
+            process_items
+            exit 0
+            ;;
 
-    *) ;;
+        *) ;;
 
     esac
 }
@@ -47,10 +47,10 @@ create_aok_groups() {
     #  changing the rest of the code.
     #
     package_groups="$(
-        set |
-            grep _APKS |
-            sed -e s/_APKS// -e s/BLOAT// -e "s/'//g" -e s/=/\|/ |
-            awk '{ print ":" $0 }'
+        set \
+            | grep _APKS \
+            | sed -e s/_APKS// -e s/BLOAT// -e "s/'//g" -e s/=/\|/ \
+            | awk '{ print ":" $0 }'
     )"
 }
 
@@ -58,12 +58,12 @@ pkg_handling() {
     action="$1"
     case "$action" in
 
-    "add" | "del") ;;
+        "add" | "del") ;;
 
-    *)
-        echo "ERROR: pkg_handling() - incorrect param: $action"
-        exit 1
-        ;;
+        *)
+            echo "ERROR: pkg_handling() - incorrect param: $action"
+            exit 1
+            ;;
     esac
 
     #
@@ -98,56 +98,56 @@ process_items() {
 
         case "$task" in
 
-        "groups") printf "%s" "$name " ;;
+            "groups") printf "%s" "$name " ;;
 
-        "list")
-            #
-            #  For pretty printing, first get all the group names
-            #  and figure out the longest. To keep the code simple
-            #  this is done on the first run of list,
-            #
-            if [ -z "$max_len" ]; then
-                # first get a list of names, in order to find longest
-                task="groups"
-                group_lst="$(process_items)"
-                task="list" # back to expected processing
+            "list")
+                #
+                #  For pretty printing, first get all the group names
+                #  and figure out the longest. To keep the code simple
+                #  this is done on the first run of list,
+                #
+                if [ -z "$max_len" ]; then
+                    # first get a list of names, in order to find longest
+                    task="groups"
+                    group_lst="$(process_items)"
+                    task="list" # back to expected processing
 
-                max_len=0
-                while true; do
-                    g="${group_lst%% *}"
-                    group_lst="${group_lst#* }"
+                    max_len=0
+                    while true; do
+                        g="${group_lst%% *}"
+                        group_lst="${group_lst#* }"
 
-                    g_len="${#g}"
-                    [ "$g_len" -gt "$max_len" ] && max_len="$g_len"
+                        g_len="${#g}"
+                        [ "$g_len" -gt "$max_len" ] && max_len="$g_len"
 
-                    [ "$group_lst" = "$g" ] && break # list done
-                done
-            fi
-            printf "[%${max_len}s]  %s\n" "$name" "$packages"
-            ;;
+                        [ "$group_lst" = "$g" ] && break # list done
+                    done
+                fi
+                printf "[%${max_len}s]  %s\n" "$name" "$packages"
+                ;;
 
-        "install")
-            if [ "$name" = "$item" ]; then
-                pkg_handling add
-                return
-            fi
-            ;;
+            "install")
+                if [ "$name" = "$item" ]; then
+                    pkg_handling add
+                    return
+                fi
+                ;;
 
-        "uninstall")
-            if [ "$item" = "core" ]; then
-                echo "ERROR: group core can not be deleted!"
+            "uninstall")
+                if [ "$item" = "core" ]; then
+                    echo "ERROR: group core can not be deleted!"
+                    exit 1
+                fi
+                if [ "$name" = "$item" ]; then
+                    pkg_handling del
+                    return
+                fi
+                ;;
+
+            *)
+                echo "ERROR: Unknown task: $task"
                 exit 1
-            fi
-            if [ "$name" = "$item" ]; then
-                pkg_handling del
-                return
-            fi
-            ;;
-
-        *)
-            echo "ERROR: Unknown task: $task"
-            exit 1
-            ;;
+                ;;
 
         esac
         [ "$lst" = "$section" ] && break # we have processed last group
diff --git a/build_fs b/build_fs
--- a/build_fs
+++ b/build_fs
@@ -84,18 +84,18 @@ ensure_real_wget_is_installed() {
     msg_1 "In order for this to work wget will be installed"
 
     case "$(detect_fs)" in
-    "$distro_alpine")
-        #  shellcheck disable=SC2086 # in this case it should expand
-        apk add $_deps
-        ;;
-    "$distro_debian" | "$distro_devuan")
-        #  shellcheck disable=SC2086 # in this case it should expand
-        apt install $_deps
-        ;;
-    *)
-        echo "Platform not recognized, can not suggest how to install"
-        error_msg "You need the following packages: $_deps"
-        ;;
+        "$distro_alpine")
+            #  shellcheck disable=SC2086 # in this case it should expand
+            apk add $_deps
+            ;;
+        "$distro_debian" | "$distro_devuan")
+            #  shellcheck disable=SC2086 # in this case it should expand
+            apt install $_deps
+            ;;
+        *)
+            echo "Platform not recognized, can not suggest how to install"
+            error_msg "You need the following packages: $_deps"
+            ;;
     esac
 
     msg_3 "Dependencies resolved"
@@ -106,77 +106,77 @@ parse_arguments() { # Multi OK 1
 
         case "$1" in
 
-        "-h" | "--help") show_help ;;
+            "-h" | "--help") show_help ;;
 
-        "-v" | "--verbose") verbose=true ;;
+            "-v" | "--verbose") verbose=true ;;
 
-        "-d" | "--debian")
-            if [ "$build_target" = "$destfs_select" ]; then
-                echo "Can not be combined: -d and -s"
+            "-d" | "--debian")
+                if [ "$build_target" = "$destfs_select" ]; then
+                    echo "Can not be combined: -d and -s"
+                    exit 1
+                fi
+                build_target="$distro_debian"
+                ;;
+
+            -g | --gentoo)
+                if [ "$build_target" = "$destfs_select" ]; then
+                    echo "Can not be combined: -g and -s"
+                    exit 1
+                fi
+                build_target="$distro_gentoo"
+                ;;
+
+            #"-D" | "--devuan")
+            #    if [ "$build_target" = "$destfs_select" ]; then
+            #        echo "Can not be combined: -D and -s"
+            #        exit 1
+            #    fi
+            #    build_target="$distro_devuan"
+            #    ;;
+
+            "-s" | "--select")
+                if [ "$build_target" = "$distro_debian" ] \
+                    || [ "$build_target" = "$distro_devuan" ]; then
+                    echo "Can not be combined: -d/-D and -s"
+                    exit 1
+                fi
+                if $pre_build_FS; then
+                    echo "Can not be combined: -p and -s"
+                    exit 1
+                fi
+                build_target="$destfs_select"
+                ;;
+
+            "-p" | "--prebuilt")
+                if [ "$build_target" = "$destfs_select" ]; then
+                    echo "Can not be combined: -p and -s"
+                    exit 1
+                fi
+                pre_build_FS=true
+                ;;
+
+            "-f" | "--force")
+                force_chroot="-f"
+                ;;
+
+            "-c" | "--clear")
+                do_clear
+                exit 0
+                ;;
+
+            "-C" | "--full_clear")
+                do_full_clear
+                exit 0
+                ;;
+
+            "-N" | "--no_compress")
+                aok_FS_do_compress=false
+                ;;
+
+            *)
+                echo "ERROR: bad param, try -h"
                 exit 1
-            fi
-            build_target="$distro_debian"
-            ;;
-
-        -g | --gentoo)
-            if [ "$build_target" = "$destfs_select" ]; then
-                echo "Can not be combined: -g and -s"
-                exit 1
-            fi
-            build_target="$distro_gentoo"
-            ;;
-
-        #"-D" | "--devuan")
-        #    if [ "$build_target" = "$destfs_select" ]; then
-        #        echo "Can not be combined: -D and -s"
-        #        exit 1
-        #    fi
-        #    build_target="$distro_devuan"
-        #    ;;
-
-        "-s" | "--select")
-            if [ "$build_target" = "$distro_debian" ] ||
-                [ "$build_target" = "$distro_devuan" ]; then
-                echo "Can not be combined: -d/-D and -s"
-                exit 1
-            fi
-            if $pre_build_FS; then
-                echo "Can not be combined: -p and -s"
-                exit 1
-            fi
-            build_target="$destfs_select"
-            ;;
-
-        "-p" | "--prebuilt")
-            if [ "$build_target" = "$destfs_select" ]; then
-                echo "Can not be combined: -p and -s"
-                exit 1
-            fi
-            pre_build_FS=true
-            ;;
-
-        "-f" | "--force")
-            force_chroot="-f"
-            ;;
-
-        "-c" | "--clear")
-            do_clear
-            exit 0
-            ;;
-
-        "-C" | "--full_clear")
-            do_full_clear
-            exit 0
-            ;;
-
-        "-N" | "--no_compress")
-            aok_FS_do_compress=false
-            ;;
-
-        *)
-            echo "ERROR: bad param, try -h"
-            exit 1
-            ;;
+                ;;
 
         esac
         shift
@@ -284,13 +284,13 @@ cache_fs_image() {
         #  Ensure basename for tar ball is used
         case "$build_target" in
 
-        "$distro_alpine" | "$destfs_select") ;; # cmd="$cmd -O $alpine_src_tb" ;;
-        "$distro_debian") ;;                    # cmd="$cmd -O $debian_src_tb" ;;
-        "$distro_devuan") ;;                    # cmd="$cmd -O $devuan_src_tb" ;;
-        "$distro_gentoo") ;;                    #cmd="wget '$src_image' -O $gentoo_src_tb" ;;
-        *)
-            error_msg "Invalid build_target: $build_target"
-            ;;
+            "$distro_alpine" | "$destfs_select") ;; # cmd="$cmd -O $alpine_src_tb" ;;
+            "$distro_debian") ;;                    # cmd="$cmd -O $debian_src_tb" ;;
+            "$distro_devuan") ;;                    # cmd="$cmd -O $devuan_src_tb" ;;
+            "$distro_gentoo") ;;                    #cmd="wget '$src_image' -O $gentoo_src_tb" ;;
+            *)
+                error_msg "Invalid build_target: $build_target"
+                ;;
         esac
 
         ensure_real_wget_is_installed
diff --git a/compress_image b/compress_image
--- a/compress_image
+++ b/compress_image
@@ -68,22 +68,22 @@ while [ -n "$1" ]; do
 
     case "$1" in
 
-    "-h" | "--help") show_help ;;
+        "-h" | "--help") show_help ;;
 
-    "-l" | "--label")
-        shift
-        tar_name="$1"
-        if [ -z "$tar_name" ]; then
-            echo "ERROR: label needs name as additional param!"
-            exit 1
-        fi
-        ;;
+        "-l" | "--label")
+            shift
+            tar_name="$1"
+            if [ -z "$tar_name" ]; then
+                echo "ERROR: label needs name as additional param!"
+                exit 1
+            fi
+            ;;
 
-    "-v" | "--verbose") verbose=true ;;
+        "-v" | "--verbose") verbose=true ;;
 
-    *)
-        error_msg "bad param, try -h"
-        ;;
+        *)
+            error_msg "bad param, try -h"
+            ;;
     esac
     shift
 done
@@ -103,29 +103,29 @@ else
     #  If no tarball name was given, try to identify what is prepared
     #  and give it a name  based on this with versions added.
     case "$(destfs_detect)" in
-    "$destfs_select")
-        tarball_fn="SelectDistro-AOK-${AOK_VERSION}"
-        ;;
-    "$distro_alpine")
-        msg_3 "Getting release details for Alpine"
-        if get_lsb_release; then
-            tarball_fn="${lsb_DistributorID}-${lsb_Release}-AOK-${AOK_VERSION}"
-        else
-            msg_4 "lsb_release unavailable, manually naming tar"
-            tarball_fn="Alpine-$(cat "$d_build_root"/etc/alpine-release)-AOK-${AOK_VERSION}"
-        fi
-        ;;
-    "$distro_debian" | "$distro_devuan")
-        msg_3 "Getting release details for Debian/Devuan"
-        if get_lsb_release; then
-            tarball_fn="${lsb_DistributorID}-${lsb_Release}-AOK-${AOK_VERSION}"
-        else
-            msg_4 "lsb_release unavailable, manually naming tar"
-            tarball_fn="Debian-$(cat "$d_build_root"/etc/debian_version)-AOK-${AOK_VERSION}"
-        fi
-        ;;
+        "$destfs_select")
+            tarball_fn="SelectDistro-AOK-${AOK_VERSION}"
+            ;;
+        "$distro_alpine")
+            msg_3 "Getting release details for Alpine"
+            if get_lsb_release; then
+                tarball_fn="${lsb_DistributorID}-${lsb_Release}-AOK-${AOK_VERSION}"
+            else
+                msg_4 "lsb_release unavailable, manually naming tar"
+                tarball_fn="Alpine-$(cat "$d_build_root"/etc/alpine-release)-AOK-${AOK_VERSION}"
+            fi
+            ;;
+        "$distro_debian" | "$distro_devuan")
+            msg_3 "Getting release details for Debian/Devuan"
+            if get_lsb_release; then
+                tarball_fn="${lsb_DistributorID}-${lsb_Release}-AOK-${AOK_VERSION}"
+            else
+                msg_4 "lsb_release unavailable, manually naming tar"
+                tarball_fn="Debian-$(cat "$d_build_root"/etc/debian_version)-AOK-${AOK_VERSION}"
+            fi
+            ;;
 
-    *) error_msg "Could not detext FS type" ;;
+        *) error_msg "Could not detext FS type" ;;
     esac
     deploy_state_is_it "$deploy_state_pre_build" && tarball_fn="$tarball_fn-pb"
 fi
